name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Install dfx
        run: |
          DFX_VERSION=0.17.0
          curl -LO https://github.com/dfinity/sdk/releases/download/$DFX_VERSION/dfx-$DFX_VERSION-x86_64-linux.tar.gz
          tar -xvzf dfx-$DFX_VERSION-x86_64-linux.tar.gz
          sudo mv dfx /usr/local/bin/dfx

      - name: install mops packages
        run: mops install

      - name: run tests
        run: mops test
