name: mops test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install DFX
        run: |
          DFX_VERSION=0.25.0
          sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          echo "$HOME/bin" >> $GITHUB_PATH

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Install mops packages
        run: mops install

      - name: Run mops test
        run: mops test
