name: mops test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ZenVoich/setup-mops@v1
        with:
          mops-version: 1

      - name: Install Motoko compiler (moc)
        run: |
          curl -LO https://github.com/dfinity/motoko/releases/download/0.10.2/moc-linux64
          chmod +x moc-linux64
          sudo mv moc-linux64 /usr/local/bin/moc

      - name: Install mops packages
        run: mops install

      - name: Run tests
        env:
          DFX_MOC_PATH: moc
        run: mops test
